name: laravel-timevault-api
services:
- name: api
  source_dir: /
  github:
    repo: kayliong/laravel-timevault-api
    branch: master
  environment_slug: php
  http_port: 8080
  health_check:
    http_path: /ping
  envs:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: "true"
  - key: APP_KEY
    value: base64:Oqwx6V6t3vC5DEADAaaxcV4I3IhXHP4z
