name: laravel-timevault-api
services:
- name: api
  source_dir: /
  github:
    repo: kayliong/laravel-timevault-api
    branch: master
  run_command: php -S 0.0.0.0:8080 -t public
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: APP_ENV
    value: production
  - key: APP_KEY
    value: Oqwx6V6t3vC5DEADAaaxcV4I3IhXHP4z