name: CI Tests

# Trigger the workflow on push to master and pull requests targeting master
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # Add database service if your tests require it
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v4

    # Setup PHP 8.4
    - name: Setup PHP 8.4
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, xml, ctype, json, curl, zip, pdo, pdo_mysql
        coverage: xdebug
        tools: composer:v2

    # Validate composer.json and composer.lock
    - name: Validate composer files
      run: composer validate

    # Cache Composer dependencies
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # Install Composer dependencies
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    # Run PHPUnit tests
    - name: Run PHPUnit tests
      run: |
        if [ -f "phpunit.xml" ] || [ -f "phpunit.xml.dist" ]; then
          ./vendor/bin/phpunit --testdox
        else
          echo "No PHPUnit configuration found, running tests directly"
          ./vendor/bin/phpunit tests/
        fi